#!/usr/bin/env bash
# xe-gmi hardware verification — run manually as root, not part of CI. See verify/README.md first.
#
#   sudo verify/run-verify.sh [verify/verify.conf]
#
# Touches exactly one PCI device (PCI= in the conf), only through the xe-gmi binary plus a raw
# restore of the snapshot on exit. Produces verify/results/<timestamp>/ with results.md,
# results.json and every command's stdout/stderr/exit/timing/before/after and a dmesg delta.
set -u
CONF="${1:-verify/verify.conf}"
[ -r "$CONF" ] || { echo "missing $CONF (copy verify/verify.conf.example)" >&2; exit 2; }
# shellcheck disable=SC1090
. "$CONF"
: "${PCI:?}" "${XE_GMI:?}" "${RESULTS_DIR:=./verify/results}" "${POWER_DELTA_W:=50}" "${CLAMP_PROBE:=1}"
: "${CLOCK_DELTA_MHZ:=200}" "${PROFILE_TEST:=1}" "${PERSIST_TEST:=1}" "${PERSIST_EXE:=/usr/local/bin/xe-gmi}"
: "${KEEP_PERSIST:=0}" "${STEP_TIMEOUT:=30}" "${UNPRIV_USER:=${SUDO_USER:-}}"

[ "$(id -u)" = 0 ] || { echo "run with sudo" >&2; exit 2; }
DEV="/sys/bus/pci/devices/$PCI"
[ -d "$DEV" ] || { echo "no PCI device $PCI" >&2; exit 2; }
[ "$(basename "$(readlink "$DEV/driver" 2>/dev/null || echo none)")" = "xe" ] || { echo "$PCI is not bound to xe; refusing" >&2; exit 2; }
[ -x "$XE_GMI" ] || { echo "$XE_GMI is not executable" >&2; exit 2; }
HW="$(for h in "$DEV"/hwmon/hwmon*; do [ "$(cat "$h/name" 2>/dev/null)" = xe ] && echo "$h" && break; done)"
TS="$(date -u +%Y%m%dT%H%M%SZ)"
OUT="$RESULTS_DIR/$TS"; mkdir -p "$OUT"
STEP=0; PASS=0; FAIL=0; SKIP=0; ABORT=0
JSON_ITEMS=()

log() { printf '%s\n' "$*" | tee -a "$OUT/log.txt"; }
dmesg_snapshot() { dmesg -T 2>/dev/null > "$1" || journalctl -k --no-pager 2>/dev/null > "$1" || : ; }
# The selected power profile is the BRACKETED token: "[base]    power_saving" -> base.
active_profile() { grep -o '\[[a-z_]*\]' "$1" | tr -d '[]'; }

# ---------------------------------------------------------------- environment record
{
  echo "timestamp_utc=$TS"; echo "kernel=$(uname -r)"; echo "distro=$(. /etc/os-release 2>/dev/null; echo "${PRETTY_NAME:-unknown}")"
  echo "pci=$PCI"; echo "device_id=$(cat "$DEV/device")"; echo "hwmon=$HW"; echo "xe_gmi=$XE_GMI"; echo "xe_gmi_sha256=$(sha256sum "$XE_GMI" | cut -d' ' -f1)"
  echo "xe_gmi_version=$("$XE_GMI" --version 2>&1)"; echo "boot_id=$(cat /proc/sys/kernel/random/boot_id)"; echo "uptime_s=$(cut -d' ' -f1 /proc/uptime)"
  echo "conf=$CONF"; cat "$CONF" | grep -vE '^\s*#' | sed 's/^/conf: /'
} > "$OUT/env.txt"
dmesg_snapshot "$OUT/dmesg-before.txt"

# ---------------------------------------------------------------- snapshot of every writable attribute
SNAP="$OUT/snapshot.txt"
{
  echo "# xe-gmi verify snapshot $TS device $PCI (path value)"
  for a in power1_max power1_cap power2_max power2_cap; do [ -f "$HW/$a" ] && echo "$HW/$a $(cat "$HW/$a")"; done
  for g in "$DEV"/tile*/gt*/freq0; do
    [ -d "$g" ] || continue
    echo "$g/min_freq $(cat "$g/min_freq")"; echo "$g/max_freq $(cat "$g/max_freq")"
    [ -f "$g/power_profile" ] && echo "$g/power_profile $(active_profile "$g/power_profile")"
  done
} > "$SNAP"
# reference (read-only) values
{
  for a in power1_crit power1_rated_max power1_max_interval power1_cap_interval energy1_input fan1_input; do [ -f "$HW/$a" ] && echo "$HW/$a $(cat "$HW/$a")"; done
  for g in "$DEV"/tile*/gt*/freq0; do for a in rpn_freq rp0_freq rpe_freq rpa_freq act_freq cur_freq; do [ -f "$g/$a" ] && echo "$g/$a $(cat "$g/$a")"; done; done
} > "$OUT/reference.txt"
cp "$(dirname "$0")/restore-from-snapshot.sh" "$OUT/restore.sh" 2>/dev/null || true
cat > "$OUT/restore.sh" <<EOS
#!/usr/bin/env bash
# Generated by run-verify.sh. Restores the snapshot taken at $TS for $PCI. Run with sudo.
exec "$(cd "$(dirname "$0")" && pwd)/restore-from-snapshot.sh" "$SNAP"
EOS
chmod +x "$OUT/restore.sh"
log "snapshot written: $SNAP"

restore_all() {
  log "restoring snapshot..."
  bash "$(dirname "$0")/restore-from-snapshot.sh" "$SNAP" >> "$OUT/log.txt" 2>&1
  # verify
  local bad=0
  while IFS=' ' read -r path value; do
    case "$path" in \#*|"") continue;; esac
    case "$(basename "$path")" in
      power_profile) cur="$(active_profile "$path")";;
      *) cur="$(tr -d '\n' < "$path" 2>/dev/null)";;
    esac
    [ "$cur" = "$value" ] || { log "RESTORE MISMATCH $path expected $value got $cur"; bad=1; }
  done < "$SNAP"
  [ $bad = 0 ] && log "restore verified: every snapshot value reads back" || log "RESTORE INCOMPLETE — check $OUT/log.txt and run $OUT/restore.sh"
}
finish() {
  restore_all
  dmesg_snapshot "$OUT/dmesg-after.txt"
  diff "$OUT/dmesg-before.txt" "$OUT/dmesg-after.txt" | grep '^>' | sed 's/^> //' > "$OUT/dmesg-delta.txt" || true
  write_results
}
trap finish EXIT

# ---------------------------------------------------------------- step runner
# run_step NAME EXPECTED_EXIT "description" -- cmd args...
run_step() {
  local name="$1" expect="$2" desc="$3"; shift 3; [ "$1" = "--" ] && shift
  STEP=$((STEP+1)); local id; id="$(printf '%02d-%s' "$STEP" "$name")"
  printf '%s\n' "$*" > "$OUT/$id.cmd"
  # before/after reads of every writable attribute
  awk '!/^#/{print $1}' "$SNAP" | while read -r p; do echo "$p $(cat "$p" 2>/dev/null | tr -d '\n')"; done > "$OUT/$id.before"
  local t0 t1 rc
  t0=$(date +%s%N)
  timeout "$STEP_TIMEOUT" "$@" > "$OUT/$id.stdout" 2> "$OUT/$id.stderr"; rc=$?
  t1=$(date +%s%N)
  echo "$rc" > "$OUT/$id.exit"; echo "$(( (t1 - t0) / 1000000 ))" > "$OUT/$id.ms"
  awk '!/^#/{print $1}' "$SNAP" | while read -r p; do echo "$p $(cat "$p" 2>/dev/null | tr -d '\n')"; done > "$OUT/$id.after"
  LAST_ID="$id"; LAST_RC="$rc"
  if [ "$rc" = "$expect" ]; then verdict PASS "$id" "$desc" "exit $expect" "exit $rc"; else verdict FAIL "$id" "$desc" "exit $expect" "exit $rc"; fi
  if dmesg 2>/dev/null | tail -n 50 | grep -qiE 'GPU HANG|gt reset|wedged|xe .*(error|timeout)'; then
    log "ABORT: suspicious dmesg after $id"; ABORT=1; exit 1
  fi
}
# check NAME "description" "expected" "observed"  (PASS if equal)
check() {
  local name="$1" desc="$2" exp="$3" obs="$4"
  STEP=$((STEP+1)); local id; id="$(printf '%02d-%s' "$STEP" "$name")"
  if [ "$exp" = "$obs" ]; then verdict PASS "$id" "$desc" "$exp" "$obs"; else verdict FAIL "$id" "$desc" "$exp" "$obs"; fi
}
check_contains() {
  local name="$1" desc="$2" needle="$3" file="$4"
  STEP=$((STEP+1)); local id; id="$(printf '%02d-%s' "$STEP" "$name")"
  if grep -qF -- "$needle" "$file"; then verdict PASS "$id" "$desc" "contains '$needle'" "found"; else verdict FAIL "$id" "$desc" "contains '$needle'" "not found in $file"; fi
}
skip() { STEP=$((STEP+1)); verdict SKIP "$(printf '%02d-%s' "$STEP" "$1")" "$2" "$3" "-"; }
verdict() {
  local v="$1" id="$2" desc="$3" exp="$4" obs="$5"
  case "$v" in PASS) PASS=$((PASS+1));; FAIL) FAIL=$((FAIL+1));; SKIP) SKIP=$((SKIP+1));; esac
  log "$v $id — $desc | expected: $exp | observed: $obs"
  JSON_ITEMS+=("{\"id\":\"$id\",\"verdict\":\"$v\",\"description\":\"$(printf '%s' "$desc" | sed 's/"/\\"/g')\",\"expected\":\"$(printf '%s' "$exp" | sed 's/"/\\"/g')\",\"observed\":\"$(printf '%s' "$obs" | sed 's/"/\\"/g')\"}")
}
write_results() {
  {
    echo "# xe-gmi hardware verification — $TS"; echo
    echo "device: $PCI ($(cat "$DEV/device"))  kernel: $(uname -r)  xe-gmi: $("$XE_GMI" --version 2>&1)"
    echo "totals: PASS=$PASS FAIL=$FAIL SKIP=$SKIP abort=$ABORT"; echo
    echo "Every step has files \$id.{cmd,stdout,stderr,exit,ms,before,after} in this directory."
    echo "snapshot.txt = values before the run; restore.sh re-applies them. dmesg-delta.txt = kernel messages during the run."; echo
    echo "## Steps"; echo; grep -E '^(PASS|FAIL|SKIP) ' "$OUT/log.txt" | sed 's/^/- /'; echo
    echo "## Snapshot (boot values)"; echo; sed 's/^/    /' "$SNAP"; echo
    echo "## Reference values"; echo; sed 's/^/    /' "$OUT/reference.txt"; echo
    echo "## dmesg delta"; echo; sed 's/^/    /' "$OUT/dmesg-delta.txt" 2>/dev/null; echo
    echo "## Notes"; echo
    echo "- Compare every FAIL's .stdout/.stderr/.before/.after against the expected behaviour documented in README (control messages) and docs/abi-notes.md (kernel interface). The kernel is the arbiter: if observed behaviour contradicts docs/abi-notes.md, record the observed value there."
    echo "- The boot values above are the ground truth for docs/abi-notes.md ('observed on hardware')."
  } > "$OUT/results.md"
  { echo "{\"timestamp\":\"$TS\",\"pci\":\"$PCI\",\"kernel\":\"$(uname -r)\",\"pass\":$PASS,\"fail\":$FAIL,\"skip\":$SKIP,\"abort\":$ABORT,\"steps\":["; local first=1; for j in "${JSON_ITEMS[@]}"; do [ $first = 1 ] || echo ","; first=0; printf '%s' "$j"; done; echo "]}"; } > "$OUT/results.json"
  log "results: $OUT/results.md"
}

X="$XE_GMI"
# ---------------------------------------------------------------- 1. read-only commands as root
run_step ro-list 0 "list exits 0" -- "$X" list
check_contains ro-list-pci "list names the device" "$PCI" "$OUT/$LAST_ID.stdout"
run_step ro-status 0 "status exits 0" -- "$X" status
run_step ro-info 0 "info exits 0" -- "$X" info
run_step ro-info-json 0 "info --json exits 0" -- "$X" info --json
run_step ro-fields 0 "fields exits 0" -- "$X" fields
ALLF="$(awk 'NR>1{print $1}' "$OUT/$LAST_ID.stdout" | grep -v '^gt<' | paste -sd, -)"
run_step ro-query-all 0 "query with every listed field exits 0" -- "$X" query --fields "$ALLF"
run_step ro-processes 0 "processes exits 0" -- "$X" processes
run_step ro-doctor 0 "doctor exits 0 with a usable device" -- "$X" doctor
check_contains doctor-usable "doctor reports the device usable" "usable" "$OUT/$LAST_ID.stdout"
run_step ro-get-pl 0 "get power-limit" -- "$X" get power-limit
run_step ro-get-clocks 0 "get clocks" -- "$X" get clocks
run_step ro-get-profile 0 "get power-profile" -- "$X" get power-profile
run_step ro-list-nvidia 3 "selecting a non-xe device exits 3" -- "$X" -i 0000:01:00.0 list
grep -qF "$PCI" "$OUT/01-ro-list.stdout" || true
check ro-no-foreign "read commands never name the NVIDIA cards" "0" "$(cat "$OUT"/*-ro-status.stdout "$OUT"/*-ro-info.stdout | grep -c '10de\|nvidia' || true)"

# ---------------------------------------------------------------- 2. power limit round trip
LIM=""; for a in power1_max power1_cap; do [ -f "$HW/$a" ] && { LIM="$HW/$a"; break; }; done
if [ -n "$LIM" ] && [ "$POWER_DELTA_W" -gt 0 ]; then
  P0=$(cat "$LIM"); P0W=$((P0 / 1000000))
  TARGET_W=$((P0W - POWER_DELTA_W)); [ "$TARGET_W" -lt $((P0W / 2)) ] && TARGET_W=$((P0W / 2))
  run_step pl-set 0 "set power-limit ${TARGET_W}W" -- "$X" set power-limit "${TARGET_W}"
  check pl-set-readback "sysfs reads the requested limit" "$((TARGET_W * 1000000))" "$(cat "$LIM")"
  check_contains pl-set-msg "message reports the effective value" "set to ${TARGET_W}.00 W" "$OUT/$LAST_ID.stdout"
  REC="/var/lib/xe-gmi/boot/$(cat /proc/sys/kernel/random/boot_id)/$PCI.defaults"
  check pl-boot-record "boot-default record exists after the first write" "yes" "$([ -f "$REC" ] && echo yes || echo no)"
  check_contains pl-boot-record-value "boot record holds the pre-write limit" " $P0" "$REC"
  run_step pl-reset 0 "reset power-limit" -- "$X" reset power-limit
  check pl-reset-readback "sysfs reads the boot limit again" "$P0" "$(cat "$LIM")"
  if [ "$CLAMP_PROBE" = 1 ]; then
    run_step pl-clamp 0 "set power-limit above boot value (driver clamp expected)" -- "$X" set power-limit "$((P0W + 50))"
    check pl-clamp-readback "readback stayed at the boot value" "$P0" "$(cat "$LIM")"
    check_contains pl-clamp-msg "message says clamped" "clamped" "$OUT/$LAST_ID.stdout"
    run_step pl-reset2 0 "reset power-limit after clamp probe" -- "$X" reset power-limit
    check pl-reset2-readback "boot limit restored" "$P0" "$(cat "$LIM")"
  else skip pl-clamp "clamp probe" "CLAMP_PROBE=0"; fi
  run_step pl-zero 2 "set power-limit 0 is refused before writing" -- "$X" set power-limit 0
  check pl-zero-untouched "limit unchanged after refused write" "$P0" "$(cat "$LIM")"
else skip pl "power limit round trip" "no writable limit or POWER_DELTA_W=0"; fi

# ---------------------------------------------------------------- 3. clocks round trip per GT
for g in "$DEV"/tile*/gt*/freq0; do
  [ -d "$g" ] || continue
  GT="$(basename "$(dirname "$g")")"; GTN="${GT#gt}"
  MIN=$(cat "$g/min_freq"); MAX=$(cat "$g/max_freq"); RPN=$(cat "$g/rpn_freq"); RP0=$(cat "$g/rp0_freq")
  NEWMAX=$((MAX - CLOCK_DELTA_MHZ))
  if [ "$CLOCK_DELTA_MHZ" -gt 0 ] && [ "$NEWMAX" -ge "$MIN" ] && [ "$NEWMAX" -ge "$RPN" ]; then
    run_step clk-$GT-set 0 "$GT: set clocks --max $NEWMAX" -- "$X" set clocks --gt "$GTN" --max "$NEWMAX"
    check clk-$GT-readback "$GT max_freq reads $NEWMAX" "$NEWMAX" "$(cat "$g/max_freq")"
    check clk-$GT-min-untouched "$GT min_freq untouched" "$MIN" "$(cat "$g/min_freq")"
    run_step clk-$GT-reset 0 "$GT: reset clocks" -- "$X" reset clocks
    check clk-$GT-reset-readback "$GT max_freq back to boot value" "$MAX" "$(cat "$g/max_freq")"
    check clk-$GT-reset-min "$GT min_freq back to boot value" "$MIN" "$(cat "$g/min_freq")"
  else skip clk-$GT "$GT clock round trip" "delta would leave [$MIN,$MAX]"; fi
  run_step clk-$GT-oob 2 "$GT: --max above rp0 is refused before writing" -- "$X" set clocks --gt "$GTN" --max "$((RP0 + 100))"
  check clk-$GT-oob-untouched "$GT max_freq unchanged after refused write" "$MAX" "$(cat "$g/max_freq")"
  echo "$GT boot min=$MIN max=$MAX rpn=$RPN rp0=$RP0 rpe=$(cat "$g/rpe_freq") rpa=$(cat "$g/rpa_freq" 2>/dev/null || echo n/a)" >> "$OUT/observed-clocks.txt"
done

# ---------------------------------------------------------------- 4. power profile
G0="$(ls -d "$DEV"/tile0/gt0/freq0 2>/dev/null)"
if [ "$PROFILE_TEST" = 1 ] && [ -f "$G0/power_profile" ]; then
  P0P="$(active_profile "$G0/power_profile")"
  OTHER=power-saving; [ "$P0P" = power_saving ] && OTHER=base
  run_step prof-set 0 "set power-profile $OTHER" -- "$X" set power-profile "$OTHER" --gt 0
  check prof-readback "gt0 power_profile selects $OTHER" "${OTHER/-/_}" "$(active_profile "$G0/power_profile")"
  run_step prof-reset 0 "reset power-profile" -- "$X" reset power-profile
  check prof-reset-readback "gt0 power_profile back to $P0P" "$P0P" "$(active_profile "$G0/power_profile")"
else skip prof "power profile round trip" "attribute absent (kernel < 6.18) or PROFILE_TEST=0"; fi

# ---------------------------------------------------------------- 5. persistence
if [ "$PERSIST_TEST" = 1 ]; then
  if [ ! -x "$PERSIST_EXE" ]; then install -m 0755 "$XE_GMI" "$PERSIST_EXE" && log "installed $XE_GMI to $PERSIST_EXE for the persistence test"; fi
  run_step pst-install 0 "persist install" -- "$X" persist install --exe "$PERSIST_EXE"
  check pst-rule "udev rule exists" "yes" "$([ -f /etc/udev/rules.d/90-xe-gmi-persist.rules ] && echo yes || echo no)"
  check_contains pst-rule-text "rule matches bind events" 'ACTION=="bind", SUBSYSTEM=="pci", ENV{DRIVER}=="xe"' /etc/udev/rules.d/90-xe-gmi-persist.rules
  if [ -n "$LIM" ] && [ "$POWER_DELTA_W" -gt 0 ]; then
    run_step pst-set 0 "sticky set power-limit ${TARGET_W}W" -- "$X" set power-limit "$TARGET_W"
    check_contains pst-conf "state file holds the limit" "$PCI pl" /etc/xe-gmi/persist.conf
    run_step pst-apply 0 "persist apply --udev-devpath (as udev would)" -- "$X" persist apply --udev-devpath "$(readlink -f "$DEV" | sed 's#^/sys##')"
    check pst-apply-readback "limit still the persisted value" "$((TARGET_W * 1000000))" "$(cat "$LIM")"
    check_contains pst-log "apply log records ok" " ok" /var/lib/xe-gmi/persist.log
    run_step pst-reset 0 "reset power-limit removes the line" -- "$X" reset power-limit
    check pst-conf-removed "state file no longer holds the limit" "0" "$(grep -c "$PCI pl" /etc/xe-gmi/persist.conf || true)"
  fi
  run_step pst-show 0 "persist show" -- "$X" persist show
  if [ "$KEEP_PERSIST" = 1 ]; then log "KEEP_PERSIST=1: leaving the udev rule and state file in place"; else
    run_step pst-remove 0 "persist remove --purge" -- "$X" persist remove --purge
    check pst-removed "rule and state removed" "no no" "$([ -f /etc/udev/rules.d/90-xe-gmi-persist.rules ] && echo yes || echo no) $([ -f /etc/xe-gmi/persist.conf ] && echo yes || echo no)"
  fi
else skip pst "persistence round trip" "PERSIST_TEST=0"; fi

# ---------------------------------------------------------------- 6. unprivileged behaviour
if [ -n "$UNPRIV_USER" ] && id "$UNPRIV_USER" >/dev/null 2>&1; then
  run_step unpriv-status 0 "status as $UNPRIV_USER exits 0" -- sudo -u "$UNPRIV_USER" "$X" status
  run_step unpriv-set 4 "set as $UNPRIV_USER exits 4 with a sudo hint" -- sudo -u "$UNPRIV_USER" "$X" set power-limit 100
  check_contains unpriv-hint "hint names the retry command" "sudo xe-gmi set power-limit 100" "$OUT/$LAST_ID.stderr"
  [ -n "$LIM" ] && check unpriv-untouched "limit unchanged by the refused write" "$(awk -v l="$LIM" '$1==l{print $2}' "$SNAP")" "$(cat "$LIM")"
else skip unpriv "unprivileged checks" "no UNPRIV_USER / SUDO_USER"; fi

# ---------------------------------------------------------------- 7. sampling sanity (device-level numbers are plausible)
run_step sample-query 0 "query rate fields" -- "$X" query --fields power.draw,utilization.gt,memory.used,memory.total,temp.pkg --no-header
read -r DRAW UTIL USED TOTAL TEMP < <(tr -d ',' < "$OUT/$LAST_ID.stdout")
check sample-draw-range "power draw between 0.5 and 400 W" "yes" "$(awk -v d="$DRAW" 'BEGIN{print (d+0>=0.5 && d+0<=400)?"yes":"no ("d")"}')"
check sample-total "VRAM total is a positive number of MiB" "yes" "$( [ "${TOTAL:-N/A}" != "N/A" ] && [ "$TOTAL" -gt 0 ] && echo yes || echo "no ($TOTAL)")"
echo "draw=$DRAW util=$UTIL used=$USED total=$TOTAL temp=$TEMP" >> "$OUT/observed-sample.txt"
log "done: PASS=$PASS FAIL=$FAIL SKIP=$SKIP"
exit 0
